import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./components/Providers";
import Header from "./components/Header";
import Footer from "./components/Footer";
import CreateTransactionModal from "./components/CreateTransactionModal";
import UserInitializer from "./components/UserInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen bg-black flex flex-col`}
      >
        <Providers>
          <UserInitializer>
            <Header />
            <main className="flex flex-col flex-1 min-h-0 mx-20 border-l border-r border-gray-500/20 bg-gray-950">
              {children}
              <CreateTransactionModal />
            </main>
            <Footer />
          </UserInitializer>
        </Providers>
      </body>
    </html>
  );
}
